Refactor keep car awake (#979)
New approach to keep car awake without using Sentry Mode for Tesla BLE and Tessie.
Added missing packages required for Tesla BLE.
Added feedback and error handling for TeslaFi (similar to what was done with Tessie).
Updated sample config file for Keep Car Awake section.

diff --git a/run/awake_start b/run/awake_start
--- a/run/awake_start
+++ b/run/awake_start
@@ -2,13 +2,82 @@
 
 if [[ ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) && ( -z "${TESLA_BLE_VIN:+x}" ) ]]
 then
-  log "Not keeping car awake using Sentry Mode."
+  log "Not configured to keep car awake."
 else
+  function nudge {
+    local retry=1
+
+    while true
+    do
+      if [[ -n "${TESSIE_API_TOKEN:+x}" ]]
+      # Use Tessie API to nudge the car
+      then
+        http_response=$(curl -s -w "%{http_code}" \
+          -H "Authorization: Bearer $TESSIE_API_TOKEN" \
+          -H "Accept: application/json" \
+          -H "User-Agent: github.com/marcone/teslausb" \
+          "https://api.tessie.com/$TESSIE_VIN/command/close_charge_port")
+
+        log "Tessie: Nudging the car."
+        # Extract HTTP status code
+        http_status="${http_response: -3}"
+        
+        # Check if HTTP status code is not 200 (OK)
+        if [ "$http_status" != "200" ]
+        then
+          # Log an error
+          log "Tessie: Failed to send command. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may be offline or asleep."
+          if [ "$retry" -lt "3" ]
+          then
+            log "Tessie: Retrying after 30s in case the connection was poor."
+            retry=$((retry+1))
+            sleep 30
+            continue
+          else
+            log "Tessie: Connection to the internet likely broken."
+            break
+          fi
+        fi
+      fi
+
+      if [[ -n "${TESLA_BLE_VIN:+x}" ]]
+      # Use Tesla BLE API to nudge the car
+      then
+        if BLE_response=$(/root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" charge-port-close 2>&1)
+        then
+          # BLE success
+          log "Tesla BLE: Successfully nudged the car to stay awake."
+
+        elif [[ ( "$BLE_response" == *"already closed"* ) || ( "$BLE_response" == *"cable connected"* ) ]]
+          # Acceptable false-negative BLE responses
+          then
+          log "Tesla BLE: Successfully nudged the car to stay awake."
+        
+        else  
+          # Log error and retry
+          log "Tesla BLE: Failed to nudge the car. There may be an issue with the BLE communication."
+          if [ "$retry" -lt "3" ]
+          then
+            log "Tesla BLE: Retrying after 30s in case the connection was poor."
+            retry=$((retry+1))
+            sleep 30
+            continue
+          else
+            log "Tesla BLE: $BLE_response"
+            break
+          fi
+        fi
+      fi
+
+      sleep 300
+      retry=1
+    done
+  }
 
   if [[ -z "${SENTRY_CASE:+x}" && -n "${TESLA_BLE_VIN:+x}" ]]
   then
-    # If unset, BLE can assume mode 2
-    SENTRY_CASE=2
+    # If BLE Sentry unset, can assume mode 3 
+    SENTRY_CASE=3
   fi
 
   case "${SENTRY_CASE}" in
@@ -20,8 +89,45 @@ else
       if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) ]]
       # Use TeslaFi API to enable Sentry Mode
       then
-        curl -s -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=true&noWake=true"
+        http_response=$(curl -s -w "%{http_code}" \
+          -H "Authorization: Bearer $TESLAFI_API_TOKEN" \
+          -H "Accept: application/json" \
+          -H "User-Agent: github.com/marcone/teslausb" \
+          "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=true&noWake=true")
+
         log "TeslaFi: Command sent to enable Sentry Mode."
+
+        # Extract HTTP status code
+        http_status="${http_response: -3}"
+                
+        # Extract response body (excluding status code)
+        response_body="${http_response:0:${#http_response}-3}"
+
+        # Check if HTTP status code is not 200 (OK)
+        if [ "$http_status" != "200" ]
+        then
+          # Log an error
+          log "TeslaFi: Failed to set Sentry Mode. Check your TESLAFI_API_TOKEN is set correctly. If it is, your car may be offline or asleep."
+        else
+          # Check if the response is in JSON format
+          if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
+          then
+            log "TeslaFi: Failed to set Sentry Mode."
+          else
+            # Parse JSON and check if "result" is true
+            result1=$(jq -r '.response' <<<"$response_body")
+            result2=$(jq -r '.result' <<<"$result1")
+            request_counter=$(jq -r '.tesla_request_counter' <<<"$response_body")
+            commands=$(jq -r '.commands' <<<"$request_counter")
+
+            if [[ "$result2" = "true" ]]
+            then
+              log "TeslaFi: Sentry Mode Enabled. Monthly command counter = $commands."
+            else
+              log "TeslaFi: Failed to set Sentry Mode. Response data: $response_body"
+            fi
+          fi
+        fi
       elif [[ -n "${TESSIE_API_TOKEN:+x}" ]]
       # Use Tessie API to enable Sentry Mode
       then
@@ -67,6 +173,12 @@ else
           log "Tesla BLE: Failed to set Sentry Mode."
         fi
       fi
+      ;;
+    3)
+      # Nudge car periodically without using Sentry Mode
+      log "Starting background task to keep car awake."
+      nudge &
+      echo $! > /tmp/keep_awake_task_pid
       ;;
     *)
       log "Invalid or no SENTRY_CASE defined."
diff --git a/run/awake_stop b/run/awake_stop
--- a/run/awake_stop
+++ b/run/awake_stop
@@ -1,52 +1,110 @@
 #!/bin/bash -eu
 
-if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) ]]
-# Use TeslaFi API to disable Sentry Mode
+if [[ ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) && ( -z "${TESLA_BLE_VIN:+x}" ) ]]
 then
-  curl -s -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=false&noWake=true"
-  log "TeslaFi: Command sent to disable Sentry Mode."
-elif [[ -n "${TESSIE_API_TOKEN:+x}" ]]
-# Use Tessie API to disable Sentry Mode
-then
-  http_response=$(curl -s -w "%{http_code}" \
-    -H "Authorization: Bearer $TESSIE_API_TOKEN" \
-    -H "Accept: application/json" \
-    -H "User-Agent: github.com/marcone/teslausb" \
-    "https://api.tessie.com/$TESSIE_VIN/command/disable_sentry")
+  exit
+fi
 
-  log "Tessie: Command sent to disable Sentry Mode."
-  # Extract HTTP status code
-  http_status="${http_response: -3}"
-          
-  # Extract response body (excluding status code)
-  response_body="${http_response:0:${#http_response}-3}"
-
-  # Check if HTTP status code is not 200 (OK)
-  if [ "$http_status" != "200" ]
-  then
-    # Log an error
-    log "Tessie: Failed to set Sentry Mode. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may not have a good connection."
-  else
-    # Check if the response is in JSON format
-    if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
+case "${SENTRY_CASE}" in
+  1 | 2)
+    if [[ ( -n "${TESLAFI_API_TOKEN:+x}" ) ]]
+    # Use TeslaFi API to disable Sentry Mode
     then
-      log "Tessie: Failed to set Sentry Mode. Response data: $response_body"
-    else
-      # Parse JSON and check if "result" is true
-      result=$(jq -r '.result' <<<"$response_body")
-      if [[ "$result" != "true" ]]
+      http_response=$(curl -s -w "%{http_code}" \
+          -H "Authorization: Bearer $TESLAFI_API_TOKEN" \
+          -H "Accept: application/json" \
+          -H "User-Agent: github.com/marcone/teslausb" \
+          "https://www.teslafi.com/feed.php?command=set_sentry_mode&sentryMode=false&noWake=true")
+      
+      log "TeslaFi: Command sent to disable Sentry Mode."
+      # Extract HTTP status code
+      http_status="${http_response: -3}"
+                
+      # Extract response body (excluding status code)
+      response_body="${http_response:0:${#http_response}-3}"
+      
+      # Check if HTTP status code is not 200 (OK)
+      if [ "$http_status" != "200" ]
       then
-        log "Tessie: Failed to set Sentry Mode. Response data: $response_body"
+        # Log an error
+        log "TeslaFi: Failed to set Sentry Mode. Check your TESLAFI_API_TOKEN is set correctly. If it is, your car may be offline or asleep."
+      else
+        # Check if the response is in JSON format
+        if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
+        then
+          log "TeslaFi: Failed to set Sentry Mode."
+        else
+          # Parse JSON and check if "result" is true
+          result1=$(jq -r '.response' <<<"$response_body")
+          result2=$(jq -r '.result' <<<"$result1")
+          request_counter=$(jq -r '.tesla_request_counter' <<<"$response_body")
+          commands=$(jq -r '.commands' <<<"$request_counter")
+      
+          if [[ "$result2" = "true" ]]
+          then
+            log "TeslaFi: Sentry Mode Disabled. Monthly command counter = $commands."
+          else
+            log "TeslaFi: Failed to set Sentry Mode. Response data: $response_body"
+          fi
+        fi
+      fi
+
+    elif [[ -n "${TESSIE_API_TOKEN:+x}" ]]
+    # Use Tessie API to disable Sentry Mode
+    then
+      http_response=$(curl -s -w "%{http_code}" \
+        -H "Authorization: Bearer $TESSIE_API_TOKEN" \
+        -H "Accept: application/json" \
+        -H "User-Agent: github.com/marcone/teslausb" \
+        "https://api.tessie.com/$TESSIE_VIN/command/disable_sentry")
+
+      log "Tessie: Command sent to disable Sentry Mode."
+      # Extract HTTP status code
+      http_status="${http_response: -3}"
+              
+      # Extract response body (excluding status code)
+      response_body="${http_response:0:${#http_response}-3}"
+
+      # Check if HTTP status code is not 200 (OK)
+      if [ "$http_status" != "200" ]
+      then
+        # Log an error
+        log "Tessie: Failed to set Sentry Mode. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may not have a good connection."
+      else
+        # Check if the response is in JSON format
+        if ! jq -e . >/dev/null 2>&1 <<<"$response_body"
+        then
+          log "Tessie: Failed to set Sentry Mode. Response data: $response_body"
+        else
+          # Parse JSON and check if "result" is true
+          result=$(jq -r '.result' <<<"$response_body")
+          if [[ "$result" != "true" ]]
+          then
+            log "Tessie: Failed to set Sentry Mode. Response data: $response_body"
+          fi
+        fi
+      fi
+
+    elif [[ -n "${TESLA_BLE_VIN:+x}" ]]
+    then
+      # Use Tesla BLE API to disable Sentry Mode
+      if /root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" sentry-mode off
+      then
+        log "Tesla BLE: Command sent to disable Sentry Mode."
+      else
+        log "Tesla BLE: Failed to set Sentry Mode."
       fi
     fi
-  fi
-elif [[ -n "${TESLA_BLE_VIN:+x}" ]]
-# Use Tesla BLE API to disable Sentry Mode
-then
-  if /root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" sentry-mode off
-  then
-    log "Tesla BLE: Command sent to disable Sentry Mode."
-  else
-    log "Tesla BLE: Failed to set Sentry Mode."
-  fi
-fi
+  ;;
+  3)
+    if [ -e /tmp/keep_awake_task_pid ]
+    then
+      log "Stopping background task that is keeping car awake."
+      kill "$(cat /tmp/keep_awake_task_pid)" || true
+      rm -f /tmp/keep_awake_task_pid
+    fi
+  ;;
+  *)
+    log "Invalid or no SENTRY_CASE defined."
+  ;;
+esac
